

#servo constants
BACK_LEFT_TIP = 31
BACK_LEFT_KNEE = 8
BACK_LEFT_HIP = 9

BACK_RIGHT_TIP = 27
BACK_RIGHT_KNEE = 23
BACK_RIGHT_HIP = 22

CENTER_LEFT_TIP = 10
CENTER_LEFT_KNEE = 11
CENTER_LEFT_HIP = 12

CENTER_RIGHT_TIP = 21
CENTER_RIGHT_KNEE = 20
CENTER_RIGHT_HIP = 19

FRONT_LEFT_TIP = 13
FRONT_LEFT_KNEE = 14
FRONT_LEFT_HIP = 15

FRONT_RIGHT_TIP = 18
FRONT_RIGHT_KNEE = 17
FRONT_RIGHT_HIP = 16

HEAD_0 = 0
HEAD_1 = 1